<?xml version="1.0" encoding="UTF-8"?>
<project name="XJGE" default="default" basedir=".">
    <description>Builds, tests, and runs the project XJGE.</description>
    
    <!-- Project version / artifact name -->
    <property name="project.version" value="4.0.0-beta17"/>
    <property name="artifact.name" value="${ant.project.name}-${project.version}"/>
    
    <!-- Override NetBeans default JAR name -->
    <property name="jar.name" location="dist/${artifact.name}.jar"/>
    <import file="nbproject/build-impl.xml"/>
    
    <!-- Provide actions to bundle sources and javadoc in jars -->
    <target description="bundle sources in a jar" name="package-sources">
        <jar basedir="src" destfile="dist/${ant.project.name}-${project.version}-sources.jar"/>
    </target>
    <target depends="-javadoc-build" description="bundle javadoc in a jar" name="package-doc">
        <jar basedir="dist/javadoc" destfile="dist/${ant.project.name}-${project.version}-javadoc.jar"/>
    </target>
</project>